# Linear Algebra - Matrices and Tensors

In [1]:
import numpy as np

In [4]:
x1=np.array([4,5,6])
print(x1)
print(x1.shape)
print(x1[0])

[4 5 6]
(3,)
4


In [6]:
#We will represent a vector as a column vector, that is having  multiple rows and a single column
x2=np.array([[6],[7],[8],[9]])
print(x2)
print(x2.shape)
print(x2[0])
print(x2[0][0])

[[6]
 [7]
 [8]
 [9]]
(4, 1)
[6]
6


In [8]:
x2=np.array([[6],[7],[8],[9]])
x2=x2.reshape(-1,)
print(x2)

[6 7 8 9]


In [9]:
x2=np.array([[6],[7],[8],[9]])
x2=x2.reshape(-1,2)
print(x2)

[[6 7]
 [8 9]]


In [11]:
#Here m is a matrix
m=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m.shape)
print(m)

m[1:,:]=2
print(m)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [2 2 2]
 [2 2 2]]


In [12]:
# Here T is a Tensor
T=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(T.shape)
print(T)

(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
#Transpose
mt=np.transpose(m)
print(m)
print(mt)

[[1 2 3]
 [2 2 2]
 [2 2 2]]
[[1 2 2]
 [2 2 2]
 [3 2 2]]


In [21]:
x=np.array([[4],[5],[8],[9]])
y=x.reshape(-1,1)
print(x.shape,y.shape)
print(x)
print(y)
print(y.transpose())
print(np.transpose(y).shape)

(4, 1) (4, 1)
[[4]
 [5]
 [8]
 [9]]
[[4]
 [5]
 [8]
 [9]]
[[4 5 8 9]]
(1, 4)


# Broadcasting

In [22]:
l=[1,2,3,4]
l=l+1
print(l)
l=l**2
print(l)

TypeError: can only concatenate list (not "int") to list

In [23]:
l=[1,2,3,4]
l=np.array(l)
l=l+1
print(l)
l=l**2
print(l)

[2 3 4 5]
[ 4  9 16 25]


In [24]:
l=[[1,2,3,4],[6,7,8,9]]
l=np.array(l)
print(l+1)
print(l**2)
print(np.sqrt(l))

[[ 2  3  4  5]
 [ 7  8  9 10]]
[[ 1  4  9 16]
 [36 49 64 81]]
[[1.         1.41421356 1.73205081 2.        ]
 [2.44948974 2.64575131 2.82842712 3.        ]]


# Linear Algebra - Matrix and Hadamard product

In [27]:
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
Y=np.array([[11,22,33],[44,55,66],[77,88,99]])
print(X.shape,Y.shape)
print(X)
print(Y)
prod=X.dot(Y)
print(prod)
prod=np.dot(X,Y)
print(prod)

(3, 3) (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 22 33]
 [44 55 66]
 [77 88 99]]
[[ 330  396  462]
 [ 726  891 1056]
 [1122 1386 1650]]
[[ 330  396  462]
 [ 726  891 1056]
 [1122 1386 1650]]


In [30]:
# Element wise multiplication
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
Y=np.eye(3)
print(X)
print(Y)
Y=Y*2+1
print(Y)
print(X*Y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[3. 1. 1.]
 [1. 3. 1.]
 [1. 1. 3.]]
[[ 3.  2.  3.]
 [ 4. 15.  6.]
 [ 7.  8. 27.]]


# Linear Algebra - Norm of a Vector

In [31]:
x=np.array([-5,3,10])
lp2=np.linalg.norm(x)
print(lp2)

11.575836902790225


In [33]:
lp1=np.linalg.norm(x,ord=1)
print(lp1)

18.0


In [34]:
lpinf=np.linalg.norm(x,ord=np.inf)
print(lpinf)

10.0
